version: '3'

services:

  caddy:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/caddy/Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"

  glossematics:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/glossematics/Dockerfile
    restart: unless-stopped
    volumes:
      - ${GLOSSEMATICS_CONF}:/etc/glossematics/conf.edn
      - ${GLOSSEMATICS_IDP_CERTIFICATE}:/etc/glossematics/idp-certificate.pem
      - ${GLOSSEMATICS_SAML_KEYSTORE}:/etc/glossematics/saml-keystore.jks
      - ${GLOSSEMATICS_FILES_DIR}:/etc/glossematics/files
      - ${GLOSSEMATICS_DB_DIR}:/etc/glossematics/db
    ports:
      - "8080:8080"
